import json
import re
from pathlib import Path


CORE_SYMPTOMS = {
    # ── Original 20 diseases ──────────────────────────────────────────────────
    "Malaria": ["Fever", "Chills", "Sweating", "Headache", "Nausea", "Vomiting", "Muscle aches", "Fatigue"],
    "Typhoid Fever": ["Prolonged fever", "Headache", "Weakness", "Abdominal pain", "Constipation", "Diarrhea", "Rose spots"],
    "Cholera": ["Profuse watery diarrhea", "Vomiting", "Muscle cramps", "Rapid dehydration", "Low blood pressure"],
    "Pneumonia": ["Cough", "Fever", "Chest pain", "Shortness of breath", "Fatigue", "Chills"],
    "Tuberculosis": ["Chronic cough", "Chest pain", "Coughing up blood", "Fatigue", "Night sweats", "Weight loss"],
    "Meningitis": ["Sudden high fever", "Stiff neck", "Severe headache", "Nausea", "Confusion", "Sensitivity to light"],
    "Dengue Fever": ["High fever", "Severe headache", "Pain behind eyes", "Joint pain", "Muscle aches", "Rash", "Mild bleeding"],
    "Dysentery": ["Bloody or mucus-filled diarrhea", "Abdominal pain", "Fever", "Tenesmus", "Dehydration"],
    "Gastroenteritis": ["Diarrhea", "Vomiting", "Abdominal pain", "Nausea", "Fever", "Weakness"],
    "Asthma": ["Wheezing", "Shortness of breath", "Chest tightness", "Cough"],
    "Chickenpox": ["Fever", "Itchy rash", "Blisters", "Fatigue", "Loss of appetite"],
    "Measles": ["High fever", "Cough", "Runny nose", "Red eyes", "Koplik spots", "Rash"],
    "Scabies": ["Severe itching", "Burrow tracks", "Rash", "Skin sores", "Night itching"],
    "Diabetes Mellitus": ["Increased thirst", "Frequent urination", "Fatigue", "Blurred vision", "Slow-healing sores"],
    "Hypertension": ["Headache", "Dizziness", "Blurred vision", "Chest pain", "Shortness of breath"],
    "Iron Deficiency Anemia": ["Fatigue", "Pale skin", "Dizziness", "Shortness of breath", "Fast heartbeat"],
    "Cystitis UTI": ["Frequent urination", "Painful urination", "Pelvic pain", "Blood in urine", "Lower abdominal pain"],
    "Helicobacteriosis PepticUlcer": ["Burning stomach pain", "Nausea", "Bloating", "Heartburn", "Loss of appetite"],
    "Common Cold": ["Runny nose", "Sore throat", "Cough", "Sneezing", "Mild fever", "Headache"],
    "Skin Fungal Infection": ["Itchy skin", "Ring-shaped rash", "Red scaly skin", "Skin peeling", "Skin lesions"],
    # ── New 30 diseases (21-50) ────────────────────────────────────────────────
    "Hepatitis A": ["Jaundice", "Fatigue", "Nausea", "Vomiting", "Abdominal pain", "Dark urine", "Loss of appetite", "Fever"],
    "Hepatitis B": ["Jaundice", "Dark urine", "Fatigue", "Yellow eyes", "Abdominal pain", "Joint pain", "Loss of appetite", "Nausea"],
    "Yellow Fever": ["High fever", "Jaundice", "Muscle aches", "Severe headache", "Nausea", "Vomiting", "Back pain", "Yellow eyes"],
    "Whooping Cough": ["Cough", "Runny nose", "Fever", "Sneezing", "Vomiting", "Fatigue", "Weakness"],
    "Mumps": ["Swollen lymph nodes", "Jaw stiffness", "Fever", "Headache", "Muscle aches", "Fatigue", "Loss of appetite"],
    "Rubella": ["Mild fever", "Rash", "Swollen lymph nodes", "Red eyes", "Runny nose", "Joint pain", "Headache"],
    "Sinusitis": ["Headache", "Nasal congestion", "Facial pain", "Runny nose", "Cough", "Sore throat", "Fever"],
    "Tonsillitis": ["Sore throat", "Difficulty swallowing", "Swollen lymph nodes", "High fever", "Headache", "Fatigue", "Loss of appetite"],
    "Ear Infection": ["Ear pain", "Fever", "Hearing loss", "Headache", "Dizziness", "Fatigue", "Pus or discharge"],
    "Conjunctivitis": ["Red eyes", "Eye discharge", "Itchy skin", "Eye pain", "Sensitivity to light", "Headache"],
    "Herpes Zoster": ["Blisters", "Rash", "Itchy rash", "Fever", "Fatigue", "Headache", "Sensitivity to light", "Skin sores"],
    "Appendicitis": ["Abdominal pain", "Fever", "Nausea", "Vomiting", "Loss of appetite", "Weakness", "Constipation"],
    "Kidney Stones": ["Back pain", "Blood in urine", "Painful urination", "Nausea", "Vomiting", "Frequent urination", "Lower abdominal pain"],
    "Sickle Cell Crisis": ["Joint pain", "Fatigue", "Pale skin", "Chest pain", "Shortness of breath", "Jaundice", "Swollen feet"],
    "Tetanus": ["Jaw stiffness", "Stiff neck", "Muscle cramps", "Fever", "Headache", "Difficulty swallowing", "Sweating"],
    "Diphtheria": ["Sore throat", "Hoarse voice", "Difficulty swallowing", "Fever", "Swollen lymph nodes", "Fatigue", "Runny nose"],
    "Ringworm": ["Ring-shaped rash", "Itchy skin", "Red scaly skin", "Skin peeling", "Skin lesions", "Hair loss"],
    "Leptospirosis": ["High fever", "Muscle aches", "Headache", "Red eyes", "Jaundice", "Vomiting", "Rash", "Dark urine"],
    "Typhus": ["Sudden high fever", "Severe headache", "Rash", "Muscle aches", "Fatigue", "Confusion", "Chills"],
    "Brucellosis": ["Fever", "Sweating", "Joint pain", "Muscle aches", "Fatigue", "Loss of appetite", "Back pain", "Night sweats"],
    "Septicemia": ["High fever", "Confusion", "Fast heartbeat", "Shortness of breath", "Low blood pressure", "Chills", "Sweating"],
    "Pelvic Inflammatory Disease": ["Pelvic pain", "Vaginal discharge", "Lower abdominal pain", "Fever", "Painful urination", "Missed period"],
    "Benign Prostatic Hyperplasia": ["Frequent urination", "Reduced urination", "Sleep disturbances", "Lower abdominal pain", "Weakness", "Back pain"],
    "Migraine": ["Severe headache", "Sensitivity to light", "Sensitivity to sound", "Nausea", "Vomiting", "Blurred vision", "Dizziness"],
    "Epilepsy": ["Seizures", "Confusion", "Confusion at night", "Muscle cramps", "Fatigue", "Weakness", "Poor coordination"],
    "Onchocerciasis": ["Severe itching", "Skin lesions", "Blurred vision", "Rash", "Skin peeling", "Swollen lymph nodes", "Weight loss"],
    "Filariasis": ["Swollen feet", "Ankle swelling", "Skin lesions", "Fever", "Skin sores", "Weakness", "Itchy skin"],
    "HIV AIDS": ["Fatigue", "Weight loss", "Night sweats", "Swollen lymph nodes", "Diarrhea", "Fever", "Rash", "Loss of appetite", "Cough", "Sore throat"],
    "Skin Abscess": ["Skin sores", "Pus or discharge", "Rash", "Fever", "Fatigue", "Swollen lymph nodes"],
    "Anaphylaxis": ["Rash", "Shortness of breath", "Fast heartbeat", "Dizziness", "Low blood pressure", "Nausea", "Swollen feet", "Sweating"],
}

CATEGORIES = {
    "Malaria": "Parasitic",
    "Scabies": "Parasitic",
    "Onchocerciasis": "Parasitic",
    "Filariasis": "Parasitic",
    "Typhoid Fever": "Bacterial",
    "Cholera": "Bacterial",
    "Tuberculosis": "Respiratory",
    "Pneumonia": "Respiratory",
    "Asthma": "Respiratory",
    "Common Cold": "Respiratory",
    "Whooping Cough": "Respiratory",
    "Sinusitis": "Respiratory",
    "Dengue Fever": "Viral",
    "Chickenpox": "Viral",
    "Measles": "Viral",
    "Hepatitis A": "Viral",
    "Hepatitis B": "Viral",
    "Yellow Fever": "Viral",
    "Mumps": "Viral",
    "Rubella": "Viral",
    "Conjunctivitis": "Viral",
    "Herpes Zoster": "Viral",
    "HIV AIDS": "Viral",
    "Gastroenteritis": "Gastrointestinal",
    "Dysentery": "Gastrointestinal",
    "Helicobacteriosis PepticUlcer": "Gastrointestinal",
    "Appendicitis": "Gastrointestinal",
    "Diabetes Mellitus": "Chronic",
    "Hypertension": "Chronic",
    "Iron Deficiency Anemia": "Chronic",
    "Sickle Cell Crisis": "Genetic",
    "Epilepsy": "Neurological",
    "Migraine": "Neurological",
    "Tonsillitis": "Bacterial",
    "Ear Infection": "Bacterial",
    "Diphtheria": "Bacterial",
    "Tetanus": "Bacterial",
    "Leptospirosis": "Bacterial",
    "Typhus": "Bacterial",
    "Brucellosis": "Bacterial",
    "Septicemia": "Bacterial",
    "Skin Abscess": "Bacterial",
    "Cystitis UTI": "Urological",
    "Kidney Stones": "Urological",
    "Benign Prostatic Hyperplasia": "Urological",
    "Skin Fungal Infection": "Fungal",
    "Ringworm": "Fungal",
    "Pelvic Inflammatory Disease": "Reproductive",
    "Anaphylaxis": "Allergic",
}

CURATED_DETAILS = {
    "Malaria": {
        "description": "A mosquito-borne parasitic infection common in tropical regions. It often causes fever, chills, sweating, headache, nausea, and fatigue.",
        "causes": "Caused by Plasmodium parasites transmitted through bites from infected female Anopheles mosquitoes.",
        "treatment": "Requires confirmatory testing and antimalarial treatment prescribed by a clinician. Severe symptoms need urgent medical care.",
        "prevention": ["Sleep under insecticide-treated bed nets", "Remove stagnant water around homes", "Use mosquito repellents and protective clothing", "Seek testing quickly for fever with chills"],
    },
    "Typhoid Fever": {
        "description": "A bacterial illness spread through contaminated food or water. It can cause prolonged fever, weakness, headache, abdominal pain, and bowel changes.",
        "causes": "Caused by Salmonella Typhi, usually after ingesting food or water contaminated with human waste.",
        "treatment": "Needs medical evaluation and antibiotics chosen by a clinician. Hydration and monitoring for complications are important.",
        "prevention": ["Drink safe or treated water", "Wash hands before eating and after toilet use", "Eat food that is well cooked and served hot", "Use vaccination where recommended"],
    },
    "Cholera": {
        "description": "An acute diarrheal infection that can cause rapid dehydration from profuse watery diarrhea and vomiting.",
        "causes": "Caused by Vibrio cholerae bacteria, usually from contaminated water or food.",
        "treatment": "Immediate oral rehydration is critical. Severe dehydration requires urgent care, IV fluids, and sometimes antibiotics.",
        "prevention": ["Use safe drinking water", "Practice hand hygiene", "Use latrines and safe sanitation", "Report suspected outbreaks early"],
    },
    "Pneumonia": {
        "description": "An infection of the lungs that can cause cough, fever, chest pain, shortness of breath, chills, and fatigue.",
        "causes": "Can be caused by bacteria, viruses, or fungi, with higher risk in children, older adults, and people with weakened immunity.",
        "treatment": "Treatment depends on cause and severity. Breathing difficulty, chest pain, or low oxygen symptoms require urgent care.",
        "prevention": ["Vaccination where available", "Avoid smoke exposure", "Wash hands regularly", "Seek care early for breathing difficulty"],
    },
    "Tuberculosis": {
        "description": "A bacterial infection that commonly affects the lungs and may cause chronic cough, night sweats, fever, weight loss, and coughing blood.",
        "causes": "Caused by Mycobacterium tuberculosis and spread through airborne droplets from an infectious person.",
        "treatment": "Requires a full multi-month TB treatment regimen supervised by healthcare workers. Do not stop treatment early.",
        "prevention": ["Test close contacts", "Improve ventilation", "Cover coughs", "Complete prescribed TB treatment"],
    },
    "Meningitis": {
        "description": "Inflammation around the brain and spinal cord that may cause sudden fever, stiff neck, severe headache, confusion, nausea, or light sensitivity.",
        "causes": "Can be caused by bacteria, viruses, or other infections. Bacterial meningitis is a medical emergency.",
        "treatment": "Requires urgent hospital evaluation. Bacterial meningitis needs rapid antibiotics and supportive care.",
        "prevention": ["Vaccination where available", "Seek urgent care for stiff neck with fever", "Avoid close contact with infected respiratory droplets"],
    },
    "Dengue Fever": {
        "description": "A mosquito-borne viral illness that can cause high fever, severe headache, pain behind the eyes, muscle and joint pain, rash, and bleeding.",
        "causes": "Caused by dengue viruses transmitted by Aedes mosquitoes.",
        "treatment": "Supportive care and hydration are important. Avoid self-medicating with aspirin or ibuprofen unless advised by a clinician.",
        "prevention": ["Prevent mosquito bites", "Remove standing water", "Use window screens and repellents", "Seek care for bleeding or severe abdominal pain"],
    },
    "Dysentery": {
        "description": "An intestinal infection causing diarrhea that may contain blood or mucus, abdominal pain, fever, and dehydration.",
        "causes": "Often caused by Shigella, amoebas, or other organisms spread through contaminated food, water, or hands.",
        "treatment": "Hydration is essential. Bloody diarrhea or signs of dehydration require medical care and may need targeted medication.",
        "prevention": ["Wash hands often", "Drink safe water", "Wash fruits and vegetables", "Use safe sanitation"],
    },
    "Gastroenteritis": {
        "description": "Inflammation of the stomach and intestines causing diarrhea, vomiting, nausea, abdominal pain, fever, and weakness.",
        "causes": "Can be caused by viruses, bacteria, parasites, contaminated food or water, or poor hygiene.",
        "treatment": "Focus on fluids and oral rehydration. Seek care for blood in stool, persistent vomiting, severe dehydration, or symptoms in young children.",
        "prevention": ["Wash hands", "Prepare food safely", "Drink treated water", "Avoid unsafe street food during outbreaks"],
    },
    "Asthma": {
        "description": "A chronic airway condition causing wheezing, cough, chest tightness, and shortness of breath that may flare with triggers.",
        "causes": "Triggers can include dust, smoke, infections, exercise, cold air, allergens, and air pollution.",
        "treatment": "Asthma is managed with clinician-guided inhalers and trigger control. Severe breathing difficulty needs emergency care.",
        "prevention": ["Avoid known triggers", "Keep rescue inhaler available if prescribed", "Reduce smoke and dust exposure", "Follow an asthma action plan"],
    },
    "Chickenpox": {
        "description": "A contagious viral illness causing fever, fatigue, and an itchy blister-like rash.",
        "causes": "Caused by the varicella-zoster virus and spread through respiratory droplets or direct contact with blisters.",
        "treatment": "Usually supportive, but infants, pregnant people, and immunocompromised patients need medical advice promptly.",
        "prevention": ["Vaccination", "Avoid contact with infected people", "Keep rash clean", "Do not scratch blisters"],
    },
    "Measles": {
        "description": "A highly contagious viral infection causing fever, cough, runny nose, red eyes, Koplik spots, and widespread rash.",
        "causes": "Caused by measles virus and spread through airborne respiratory droplets.",
        "treatment": "Supportive care and monitoring. Complications can be serious, especially in children, pregnant people, and malnourished patients.",
        "prevention": ["MMR vaccination", "Isolate suspected cases", "Improve nutrition and vitamin A where recommended"],
    },
    "Scabies": {
        "description": "A contagious skin infestation causing intense itching, night itching, rash, and small burrow tracks.",
        "causes": "Caused by mites that spread through close skin contact and shared bedding or clothing.",
        "treatment": "Requires scabicide treatment for the patient and close contacts, plus washing bedding and clothes.",
        "prevention": ["Treat close contacts", "Wash bedding and clothes in hot water", "Avoid sharing clothing or bedding during infection"],
    },
    "Diabetes Mellitus": {
        "description": "A chronic condition where blood sugar remains too high, causing thirst, frequent urination, fatigue, blurred vision, and slow-healing wounds.",
        "causes": "Related to insufficient insulin production, insulin resistance, genetics, weight, diet, and other risk factors.",
        "treatment": "Managed with blood sugar monitoring, diet, exercise, medicines, and regular clinical follow-up.",
        "prevention": ["Maintain healthy weight", "Exercise regularly", "Choose balanced meals", "Screen early if at risk"],
    },
    "Hypertension": {
        "description": "Persistently high blood pressure that may be silent or cause headache, dizziness, blurred vision, chest pain, or shortness of breath.",
        "causes": "Risk factors include age, family history, salt intake, kidney disease, stress, alcohol, and inactivity.",
        "treatment": "Managed with lifestyle changes, regular blood pressure checks, and medication when prescribed.",
        "prevention": ["Reduce salt intake", "Exercise regularly", "Limit alcohol", "Check blood pressure routinely"],
    },
    "Iron Deficiency Anemia": {
        "description": "Low red blood cell capacity due to insufficient iron, often causing fatigue, pale skin, dizziness, shortness of breath, and fast heartbeat.",
        "causes": "Can result from poor iron intake, blood loss, pregnancy, parasites, or absorption problems.",
        "treatment": "Treatment depends on cause and may include iron supplementation, diet changes, and investigation for blood loss.",
        "prevention": ["Eat iron-rich foods", "Treat parasites where present", "Use prenatal care in pregnancy", "Screen children and high-risk adults"],
    },
    "Cystitis UTI": {
        "description": "A urinary tract infection affecting the bladder, often causing painful urination, frequent urination, pelvic pain, and lower abdominal discomfort.",
        "causes": "Usually caused by bacteria entering the urinary tract.",
        "treatment": "Needs medical assessment when symptoms are persistent, recurrent, associated with fever, or occur during pregnancy.",
        "prevention": ["Drink enough fluids", "Do not delay urination", "Practice good hygiene", "Seek care early for fever or back pain"],
    },
    "Helicobacteriosis PepticUlcer": {
        "description": "A stomach infection linked with peptic ulcers, burning stomach pain, nausea, bloating, heartburn, and reduced appetite.",
        "causes": "Often caused by Helicobacter pylori bacteria that irritate the stomach lining.",
        "treatment": "Confirmed H. pylori infection is treated with clinician-prescribed combination therapy.",
        "prevention": ["Practice hand hygiene", "Use safe water", "Avoid unnecessary NSAID use", "Seek care for black stools or severe pain"],
    },
    "Common Cold": {
        "description": "A usually mild viral upper respiratory infection causing runny nose, sore throat, cough, sneezing, mild fever, and headache.",
        "causes": "Caused by respiratory viruses spread through droplets, close contact, and contaminated hands.",
        "treatment": "Supportive care with rest, fluids, and symptom relief. Seek care if breathing difficulty, persistent high fever, or worsening symptoms occur.",
        "prevention": ["Wash hands", "Cover coughs and sneezes", "Avoid close contact when ill", "Clean frequently touched surfaces"],
    },
    "Skin Fungal Infection": {
        "description": "A fungal infection of the skin causing itching, ring-shaped or red scaly patches, peeling skin, and skin lesions.",
        "causes": "Caused by various fungi including dermatophytes; spread through direct contact, shared items, or warm moist environments.",
        "treatment": "Antifungal creams or oral medication as prescribed. Keep affected area dry and clean.",
        "prevention": ["Keep skin dry", "Avoid sharing personal items", "Wear breathable footwear", "Treat promptly to prevent spread"],
    },
    # ── 30 new diseases ───────────────────────────────────────────────────────
    "Hepatitis A": {
        "description": "A viral liver infection spread through contaminated food or water, causing jaundice, fatigue, nausea, vomiting, and dark urine.",
        "causes": "Caused by the hepatitis A virus (HAV), typically via contaminated water or food prepared by an infected person.",
        "treatment": "No specific antiviral; supportive care with rest, fluids, and avoiding alcohol. Most cases resolve on their own.",
        "prevention": ["Vaccination", "Drink safe water", "Wash hands thoroughly", "Practice food hygiene"],
    },
    "Hepatitis B": {
        "description": "A serious liver infection caused by the hepatitis B virus, potentially becoming chronic and leading to liver cirrhosis or cancer.",
        "causes": "Spread through contact with infected blood, sexual contact, or from mother to child during birth.",
        "treatment": "Acute cases are managed with supportive care. Chronic hepatitis B requires antiviral medication under medical supervision.",
        "prevention": ["Vaccination", "Use condoms", "Avoid sharing needles or razors", "Screen pregnant women"],
    },
    "Yellow Fever": {
        "description": "A viral hemorrhagic disease transmitted by Aedes mosquitoes causing high fever, jaundice, muscle pain, and in severe cases, organ failure.",
        "causes": "Caused by the yellow fever flavivirus transmitted by Aedes aegypti and other Aedes mosquito species.",
        "treatment": "Supportive care only — rest, fluids, and symptom management. No specific antiviral exists. Severe cases need hospital care.",
        "prevention": ["Vaccination (single dose for lifelong protection)", "Mosquito control", "Use repellents and protective clothing"],
    },
    "Whooping Cough": {
        "description": "A highly contagious bacterial respiratory infection characterised by severe coughing fits that may end with a whooping sound and vomiting.",
        "causes": "Caused by Bordetella pertussis bacteria, spread through airborne droplets from coughing or sneezing.",
        "treatment": "Antibiotics (erythromycin, azithromycin) are most effective early. Hospitalisation may be needed in infants.",
        "prevention": ["Vaccination (DTaP/Tdap)", "Isolate infected individuals", "Vaccinate pregnant women to protect newborns"],
    },
    "Mumps": {
        "description": "A contagious viral infection that primarily causes painful swelling of the salivary glands (parotitis) and jaw stiffness.",
        "causes": "Caused by the mumps paramyxovirus, spread through saliva and respiratory droplets.",
        "treatment": "Supportive care: rest, fluids, pain relief (paracetamol), and cold/warm compresses on swollen glands.",
        "prevention": ["MMR vaccination", "Isolate infected individuals", "Wash hands frequently"],
    },
    "Rubella": {
        "description": "A mild contagious viral illness causing a fine pink rash, mild fever, and swollen lymph nodes. Dangerous in pregnancy.",
        "causes": "Caused by the rubella virus, spread through respiratory droplets.",
        "treatment": "Supportive care only. Pregnant women exposed to rubella require urgent specialist assessment.",
        "prevention": ["MMR vaccination", "Immunise all women of childbearing age", "Avoid contact with pregnant women if infected"],
    },
    "Sinusitis": {
        "description": "Inflammation of the sinuses causing facial pain, nasal congestion, headache, and runny nose, often following a cold.",
        "causes": "Usually caused by viral upper respiratory infections; may become bacterial. Allergies and structural issues are also triggers.",
        "treatment": "Steam inhalation, saline rinses, decongestants for symptom relief. Bacterial sinusitis may need antibiotics from a clinician.",
        "prevention": ["Treat colds promptly", "Manage allergies", "Avoid cigarette smoke", "Stay hydrated"],
    },
    "Tonsillitis": {
        "description": "Inflammation of the tonsils causing severe sore throat, difficulty swallowing, high fever, and swollen lymph nodes.",
        "causes": "Most commonly caused by group A Streptococcus bacteria or viral infections (adenovirus, EBV).",
        "treatment": "Rest, fluids, and pain relief. Bacterial tonsillitis requires antibiotics. Recurrent cases may need tonsillectomy.",
        "prevention": ["Wash hands", "Avoid sharing utensils", "Avoid close contact with infected individuals"],
    },
    "Ear Infection": {
        "description": "An infection of the middle ear (otitis media) causing ear pain, fever, hearing loss, and sometimes discharge.",
        "causes": "Often follows a respiratory infection. Caused by bacteria (S. pneumoniae, H. influenzae) or viruses.",
        "treatment": "Most mild cases resolve on their own. Antibiotics are prescribed for severe or persistent cases by a clinician.",
        "prevention": ["Vaccinate against pneumococcus and Hib", "Breastfeed infants", "Avoid secondhand smoke", "Treat respiratory infections promptly"],
    },
    "Conjunctivitis": {
        "description": "Inflammation of the conjunctiva (pink eye) causing red eyes, discharge, itching, and sensitivity to light.",
        "causes": "Can be viral, bacterial, or allergic. Viral and bacterial forms are highly contagious.",
        "treatment": "Viral: supportive (cool compresses, lubricating drops). Bacterial: antibiotic eye drops from a clinician.",
        "prevention": ["Wash hands frequently", "Do not touch eyes", "Do not share towels or eye drops", "Clean contact lenses properly"],
    },
    "Herpes Zoster": {
        "description": "Reactivation of the chickenpox virus (VZV) in nerve ganglia, causing a painful blistering rash in a stripe pattern on one side of the body.",
        "causes": "Caused by reactivation of the varicella-zoster virus (VZV), triggered by stress, immunosuppression, or ageing.",
        "treatment": "Antiviral medications (aciclovir, valaciclovir) are most effective within 72 hours of rash onset. Pain management is important.",
        "prevention": ["Shingles vaccine for older adults", "Avoid contact with people who have chickenpox if you never had it"],
    },
    "Appendicitis": {
        "description": "Acute inflammation of the appendix causing sudden worsening abdominal pain (migrating to the right lower side), fever, nausea, and vomiting.",
        "causes": "Usually caused by a blockage in the appendix lumen by stool, mucus, or infection, leading to bacterial overgrowth.",
        "treatment": "Surgical removal of the appendix (appendicectomy) is the standard treatment. Antibiotics may be used in selected mild cases.",
        "prevention": ["High-fibre diet may reduce risk", "Seek care early for persistent abdominal pain"],
    },
    "Kidney Stones": {
        "description": "Hard mineral deposits forming in the kidneys, causing severe flank or back pain, blood in urine, and painful urination.",
        "causes": "Caused by high concentrations of minerals (calcium, oxalate, uric acid) in urine, often due to dehydration or diet.",
        "treatment": "Small stones may pass with fluids and pain relief. Larger stones need lithotripsy, ureteroscopy, or surgical removal.",
        "prevention": ["Drink plenty of water daily", "Reduce salt and animal protein intake", "Limit oxalate-rich foods", "Follow dietary advice from a clinician"],
    },
    "Sickle Cell Crisis": {
        "description": "A painful episode in sickle cell disease where sickle-shaped red blood cells block blood vessels, causing severe bone pain, fatigue, and organ complications.",
        "causes": "Triggered by infection, dehydration, cold, stress, or high altitude in people with sickle cell disease.",
        "treatment": "Pain relief, fluids, oxygen, and treatment of any triggering infection under medical supervision.",
        "prevention": ["Stay well hydrated", "Avoid extreme temperatures", "Prevent infections with vaccines and prophylactic antibiotics", "Regular haematology follow-up"],
    },
    "Tetanus": {
        "description": "A life-threatening bacterial infection causing painful muscle stiffness and spasms, especially jaw stiffness (trismus/lockjaw).",
        "causes": "Caused by Clostridium tetani toxin entering through wounds, burns, or cuts exposed to soil or animal faeces.",
        "treatment": "Tetanus immunoglobulin, wound cleaning, antibiotics, and intensive care for muscle spasms. ICU admission often required.",
        "prevention": ["Vaccination (DTP, Td boosters)", "Proper wound care and cleaning", "Seek care promptly for deep wounds"],
    },
    "Diphtheria": {
        "description": "A serious bacterial infection of the throat and airways causing sore throat, hoarse voice, a grey membrane in the throat, and breathing difficulty.",
        "causes": "Caused by Corynebacterium diphtheriae, spread through respiratory droplets and contaminated surfaces.",
        "treatment": "Diphtheria antitoxin and antibiotics (penicillin, erythromycin) under hospital care.",
        "prevention": ["Vaccination (DTP)", "Isolate infected individuals", "Close contact tracing and prophylaxis"],
    },
    "Ringworm": {
        "description": "A contagious fungal skin infection (not a worm) causing ring-shaped red scaly patches, itching, and skin peeling.",
        "causes": "Caused by dermatophyte fungi; spread through direct skin contact, shared towels, bedding, or infected animals.",
        "treatment": "Topical antifungal creams (clotrimazole, miconazole) for most cases; oral antifungals for scalp or nail involvement.",
        "prevention": ["Keep skin dry", "Avoid sharing personal items", "Treat infected animals", "Wash hands after handling animals"],
    },
    "Leptospirosis": {
        "description": "A bacterial infection contracted from water or soil contaminated with animal urine, causing high fever, muscle pain, red eyes, and jaundice.",
        "causes": "Caused by Leptospira bacteria; often acquired by contact with contaminated flood water, soil, or infected animals.",
        "treatment": "Antibiotics (doxycycline, penicillin, ceftriaxone). Severe cases (Weil's disease) need intensive hospital care.",
        "prevention": ["Avoid contact with flood water", "Wear protective footwear in endemic areas", "Vaccinate livestock", "Cover cuts and wounds"],
    },
    "Typhus": {
        "description": "A group of bacterial diseases transmitted by lice, fleas, or mites, causing sudden high fever, severe headache, rash, and confusion.",
        "causes": "Epidemic typhus is caused by Rickettsia prowazekii (lice-borne). Murine typhus by R. typhi (flea-borne).",
        "treatment": "Doxycycline is the first-line treatment; usually curative when started early.",
        "prevention": ["Louse and flea control", "Improve sanitation", "Treat clothing and bedding", "Avoid contact with lice-infested individuals"],
    },
    "Brucellosis": {
        "description": "A bacterial zoonotic infection causing fever, sweating, joint pain, fatigue, and weight loss; often from consumption of unpasteurised dairy.",
        "causes": "Caused by Brucella species from infected animals (cattle, goats, pigs), spread via unpasteurised milk, cheese, or direct animal contact.",
        "treatment": "Combination antibiotic therapy (doxycycline + rifampicin or streptomycin) for 6 weeks under medical supervision.",
        "prevention": ["Pasteurise or boil milk and dairy", "Wear gloves when handling animals or carcasses", "Vaccinate livestock"],
    },
    "Septicemia": {
        "description": "A life-threatening infection in the bloodstream (sepsis) causing high fever, confusion, rapid heart rate, breathing difficulty, and low blood pressure.",
        "causes": "Usually caused by bacterial infections that spread into the blood from any site (lungs, urinary tract, skin, abdomen).",
        "treatment": "Medical emergency requiring IV antibiotics, fluids, and intensive care. Do not delay seeking emergency care.",
        "prevention": ["Treat infections promptly", "Practice hand hygiene", "Vaccinate against causative pathogens", "Seek early care for worsening illness"],
    },
    "Pelvic Inflammatory Disease": {
        "description": "An infection of the female reproductive organs causing pelvic pain, vaginal discharge, fever, and potentially infertility if untreated.",
        "causes": "Usually caused by sexually transmitted bacteria (Chlamydia, Gonorrhoea) or other vaginal bacteria ascending to the uterus and fallopian tubes.",
        "treatment": "Antibiotics (combination regimens) prescribed by a clinician. Severe cases require hospitalisation.",
        "prevention": ["Use condoms consistently", "Get tested and treated for STIs", "Avoid douching", "Seek early care for unusual discharge or pelvic pain"],
        "genderSpecific": "female",
    },
    "Benign Prostatic Hyperplasia": {
        "description": "Non-cancerous enlargement of the prostate gland causing urinary symptoms including frequent urination, weak stream, and incomplete bladder emptying.",
        "causes": "Related to hormonal changes and ageing in men. More common after age 50.",
        "treatment": "Lifestyle changes, medications (alpha-blockers, 5-alpha reductase inhibitors), or surgery depending on severity.",
        "prevention": ["Regular health check-ups after 50", "Maintain healthy weight", "Stay physically active"],
        "genderSpecific": "male",
    },
    "Migraine": {
        "description": "A neurological disorder causing recurrent severe one-sided headaches with throbbing pain, nausea, and sensitivity to light and sound.",
        "causes": "Exact cause unclear; triggers include stress, hormonal changes, certain foods, alcohol, sleep disruption, and bright lights.",
        "treatment": "Pain relief (paracetamol, ibuprofen, triptans for severe attacks). Preventive medications if attacks are frequent.",
        "prevention": ["Identify and avoid personal triggers", "Maintain regular sleep and eating schedules", "Manage stress", "Stay hydrated"],
    },
    "Epilepsy": {
        "description": "A neurological disorder characterised by recurrent unprovoked seizures due to abnormal electrical activity in the brain.",
        "causes": "Can be caused by brain injury, stroke, infections, genetic factors, or may be idiopathic (unknown cause).",
        "treatment": "Antiepileptic drugs (AEDs) under neurology supervision. Surgery or vagus nerve stimulation for drug-resistant cases.",
        "prevention": ["Protect head from injury", "Treat brain infections early", "Take AEDs as prescribed", "Avoid seizure triggers (alcohol, sleep deprivation)"],
    },
    "Onchocerciasis": {
        "description": "A parasitic infection (river blindness) caused by worms transmitted by blackfly bites, causing intense itching, skin lesions, and vision loss.",
        "causes": "Caused by Onchocerca volvulus roundworms transmitted by Simulium blackfly bites near fast-flowing rivers.",
        "treatment": "Ivermectin (annual or semi-annual doses) controls the disease. Community-wide treatment programmes exist.",
        "prevention": ["Mass drug administration with ivermectin", "Blackfly control", "Avoid rivers and blackfly habitats in endemic areas"],
    },
    "Filariasis": {
        "description": "A parasitic disease caused by thread-like worms transmitted by mosquitoes, causing lymphoedema (swollen limbs), elephantiasis, and skin thickening.",
        "causes": "Caused by Wuchereria bancrofti and other filarial worms transmitted by Culex and other mosquito species.",
        "treatment": "Diethylcarbamazine (DEC) or ivermectin and albendazole combinations. Lymphoedema management with care and hygiene.",
        "prevention": ["Mosquito bite prevention", "Mass drug administration programmes", "Use bed nets and repellents"],
    },
    "HIV AIDS": {
        "description": "HIV destroys immune cells over time, leading to AIDS — a state of severe immune deficiency making the body vulnerable to opportunistic infections.",
        "causes": "Caused by the human immunodeficiency virus (HIV), transmitted through blood, sexual contact, or mother to child.",
        "treatment": "Antiretroviral therapy (ART) suppresses the virus, preserves immunity, and allows near-normal life. Treatment is lifelong.",
        "prevention": ["Use condoms consistently", "HIV testing and knowing your status", "Pre-exposure prophylaxis (PrEP) for high-risk individuals", "Prevent mother-to-child transmission with ART"],
    },
    "Skin Abscess": {
        "description": "A localised collection of pus under the skin (boil or abscess) causing a painful, swollen, red lump that may discharge pus.",
        "causes": "Usually caused by Staphylococcus aureus bacteria entering through broken skin, hair follicles, or sweat glands.",
        "treatment": "Warm compresses for small abscesses. Surgical incision and drainage for larger or painful abscesses. Antibiotics if spreading infection.",
        "prevention": ["Maintain skin hygiene", "Do not squeeze or puncture skin lesions", "Treat cuts and wounds promptly", "Manage diabetes and immune conditions"],
    },
    "Anaphylaxis": {
        "description": "A severe life-threatening allergic reaction causing rash, breathing difficulty, swelling, rapid heart rate, and dangerous drop in blood pressure.",
        "causes": "Triggered by allergens such as insect stings, certain foods (nuts, shellfish), medications (penicillin), or latex.",
        "treatment": "MEDICAL EMERGENCY. Epinephrine (adrenaline) injection immediately, then seek emergency hospital care.",
        "prevention": ["Know and avoid allergens", "Carry an epinephrine auto-injector if prescribed", "Wear a medical alert bracelet", "Inform healthcare providers of allergies"],
    },
}


SYMPTOM_DESCRIPTIONS = {
    "Malaria": {
        "Fever": "High-grade fever (often 38.5–40°C) that comes in waves, typically spiking every 48–72 hours as parasites burst from red blood cells. The cycle goes: sudden intense cold/shivering → scorching hot fever → drenching sweat → brief relief, then repeats.",
        "Chills": "Intense, uncontrollable shaking and feeling bitterly cold even in warm weather, usually starting 30–60 minutes before the fever spike.",
        "Sweating": "Heavy, drenching sweat that follows the fever peak, often soaking clothes and bedding. This sweating phase is when the fever temporarily breaks.",
        "Headache": "Intense, pulsating pain felt behind the eyes and across the forehead, worsening with movement or bright light — distinctly more severe than a tension headache.",
        "Nausea": "Persistent queasiness that accompanies the fever spike, often making eating impossible.",
        "Vomiting": "Occurs during or shortly after the fever spike, triggered by the nausea and the parasitic toxins released into the bloodstream.",
        "Muscle aches": "Deep, widespread muscle and bone pain throughout the body, similar to severe influenza.",
        "Fatigue": "Extreme exhaustion between fever episodes — the person is unable to stand or perform normal activities.",
    },
    "Typhoid Fever": {
        "Prolonged fever": "Fever rises gradually over 3–5 days and stays persistently high (38.8–40°C), often without the periodic spiking-and-breaking pattern of malaria. It can persist for 3–4 weeks if untreated — unlike viral fevers that resolve within a week.",
        "Headache": "Dull, constant headache across the forehead, present throughout the illness.",
        "Weakness": "Progressive exhaustion and muscle weakness that increases as the days pass.",
        "Abdominal pain": "Dull or cramping pain in the right lower or central abdomen, sometimes tender when pressed.",
        "Constipation": "Common in early typhoid — the bowel slows down before diarrhoea may develop in later stages.",
        "Diarrhea": "In later stages, loose 'pea-soup' coloured stools may replace constipation.",
        "Rose spots": "Small (2–4mm), flat, faint pink spots on the chest and abdomen that appear in the first or second week. They blanch (fade) when pressed and last 2–5 days. Often missed but classic and diagnostic.",
    },
    "Cholera": {
        "Profuse watery diarrhea": "Sudden, massive, painless diarrhoea that looks like 'rice water' — pale, cloudy liquid with tiny white flecks. Volume can reach 10–20 litres per day in severe cases, unlike any other diarrhoeal illness.",
        "Vomiting": "Effortless vomiting of clear or cloudy fluid alongside the diarrhoea, typically without nausea.",
        "Muscle cramps": "Severe, very painful cramping in the leg muscles and abdomen due to rapid loss of potassium and sodium.",
        "Rapid dehydration": "Skin loses its elasticity (stays tented when pinched), eyes appear sunken, mouth becomes extremely dry, and urine output stops — all within hours.",
        "Low blood pressure": "Blood pressure drops dangerously as fluid loss leads to circulatory collapse — the person feels faint and may lose consciousness.",
    },
    "Pneumonia": {
        "Cough": "Productive cough bringing up thick, discoloured phlegm (yellow, green, or rusty-brown). The cough is painful and worsens with deep breathing — distinctly more severe than a cold cough.",
        "Fever": "High fever (38.5–40°C) with chills, often with a sudden onset. Unlike TB, it is acute rather than gradual.",
        "Chest pain": "Sharp, stabbing chest pain that worsens with every breath, cough, or movement. Located on one side where the affected lung is inflamed (pleuritic pain).",
        "Shortness of breath": "Breathing becomes rapid and laboured. The person may feel unable to get enough air, especially lying flat.",
        "Fatigue": "Extreme tiredness out of proportion to the fever, making walking or talking difficult.",
        "Chills": "Repeated episodes of shivering and feeling intensely cold, particularly at illness onset.",
    },
    "Tuberculosis": {
        "Chronic cough": "A persistent cough lasting more than 3 weeks that worsens over time — unlike a cold, it does not resolve. It starts dry, becoming productive with mucus. This duration is the key distinguishing feature.",
        "Chest pain": "A dull ache or tightness deep in the chest, sometimes worsening when breathing deeply or coughing.",
        "Coughing up blood": "Streaks of bright red blood in phlegm (haemoptysis). May range from small flecks to larger amounts. This is an urgent warning sign.",
        "Fatigue": "Progressive, severe exhaustion building over weeks — distinct from ordinary tiredness. The person becomes unable to work or perform daily tasks.",
        "Night sweats": "Drenching sweats during sleep that soak clothing and bedding despite normal or cool room temperature — a characteristic and distinguishing feature.",
        "Weight loss": "Gradual, unexplained loss of weight and muscle mass over weeks to months, often 5–10kg or more, without intentional dieting.",
    },
    "Meningitis": {
        "Sudden high fever": "Fever rises very rapidly to 39–40°C or higher, often within hours of first feeling unwell.",
        "Stiff neck": "The neck becomes rigid and extremely painful. The person cannot touch their chin to their chest — any attempt causes severe pain. This is a critical warning sign absent in most other fevers.",
        "Severe headache": "Often described as 'the worst headache of my life' — an extremely intense, diffuse, crushing pain, unlike any ordinary headache. The combination with stiff neck is highly alarming.",
        "Nausea": "Strong nausea, often with vomiting, accompanying the headache.",
        "Confusion": "Disorientation, difficulty thinking, unusual behaviour, or altered consciousness — from drowsiness to unresponsiveness.",
        "Sensitivity to light": "Even ordinary room light causes intense pain, making the person keep eyes shut and hide in darkness (photophobia). This is absent in most other headache conditions.",
    },
    "Dengue Fever": {
        "High fever": "Sudden onset of very high fever (39–40°C) starting 4–10 days after a mosquito bite. Unlike malaria, the fever is typically continuous rather than periodic.",
        "Severe headache": "Intense headache, usually felt directly behind the eyes, worsening with eye movement.",
        "Pain behind eyes": "A distinctive, deep, aching pain directly behind the eyeballs — particularly noticeable when moving the eyes. This retro-orbital pain is a characteristic feature.",
        "Joint pain": "Severe aching in joints — knees, ankles, hips — so intense that dengue was historically called 'breakbone fever'.",
        "Muscle aches": "Intense muscle pain, particularly in the back and limbs.",
        "Rash": "Appears 3–5 days after fever onset as a red flush or measles-like spots on the chest, spreading to the limbs. Distinctively shows 'white islands in a red sea' — patches of normal skin surrounded by redness. Unlike chickenpox, it is usually not itchy and does not blister.",
        "Mild bleeding": "Tiny pinpoint red or purple spots under the skin (petechiae), nosebleeds, or gum bleeding. Black stools or blood in urine are dangerous warning signs requiring urgent care.",
    },
    "Dysentery": {
        "Bloody or mucus-filled diarrhea": "Frequent passage of small amounts of stool mixed with bright red blood and/or thick mucus — slimy, bloodstained stools. Unlike cholera's rice-water diarrhoea, dysentery stool is small in volume but contains visible blood and mucus.",
        "Abdominal pain": "Severe, cramping lower abdominal pain coming in waves, typically just before passing stool.",
        "Fever": "Moderate to high fever (38–40°C) from the start.",
        "Tenesmus": "A painful, urgent feeling of needing to pass stool even when the bowel is nearly empty. The person strains repeatedly but passes only small amounts of blood and mucus — deeply distressing.",
        "Dehydration": "Progressive fluid loss causing dry mouth, reduced urine, and weakness from frequent stools.",
    },
    "Gastroenteritis": {
        "Diarrhea": "Loose or watery stools, usually without blood, 3–10 times per day.",
        "Vomiting": "Forceful ejection of stomach contents, often preceding diarrhoea by several hours.",
        "Abdominal pain": "Cramping pain across the lower or central abdomen, often relieved briefly after passing stool.",
        "Nausea": "Persistent queasiness reducing the desire to eat or drink.",
        "Fever": "Mild to moderate fever (37.5–38.5°C) — lower than in bacterial infections like typhoid.",
        "Weakness": "General tiredness mainly from fluid and electrolyte loss.",
    },
    "Asthma": {
        "Wheezing": "A high-pitched, musical whistling sound when breathing out (and sometimes in), heard clearly or even across a room. Caused by air being forced through narrowed airways — absent in most other conditions.",
        "Shortness of breath": "Feeling unable to breathe in enough air, especially with exertion, cold air, or during a flare. The person may speak in short sentences or whisper.",
        "Chest tightness": "A sensation of pressure or constriction in the chest, as if a band is being tightened around it — not painful like pleurisy, but restrictive.",
        "Cough": "Often worse at night or early morning — dry, repetitive, triggered by exercise, cold, dust, or smoke. In some people, cough is the only symptom of asthma.",
    },
    "Chickenpox": {
        "Fever": "Mild to moderate fever (37.8–38.9°C) appearing 1–2 days before the rash. In children it is usually mild; in adults it can be higher.",
        "Itchy rash": "Begins as small flat red spots (macules) → raised bumps (papules) → clear fluid-filled blisters (vesicles) → crusts over. New crops appear for 5–7 days, so all stages coexist at the same time. Starts on the scalp, face, and trunk before spreading to limbs. Unlike dengue rash, it is intensely itchy. Unlike HIV rash, it blisters.",
        "Blisters": "Clear, dewdrop-like blisters on a red base, 2–4mm in size. Each blister is delicate — it breaks easily and scabs over within 1–2 days.",
        "Fatigue": "Significant tiredness beginning before the rash and persisting throughout.",
        "Loss of appetite": "Reduced desire to eat, especially if blisters develop inside the mouth making eating painful.",
    },
    "Measles": {
        "High fever": "Begins 2–4 days before the rash and is often very high (39–40.5°C) — the highest of any common childhood illness.",
        "Cough": "A harsh, barking cough that is persistent and dry throughout the illness.",
        "Runny nose": "Profuse, watery nasal discharge from the start.",
        "Red eyes": "Marked redness and watering of the eyes with sensitivity to light, giving a sorrowful appearance.",
        "Koplik spots": "Tiny white or bluish-white spots with a red ring, seen inside the cheeks opposite the molar teeth 1–2 days before the rash appears. These are unique to measles and highly diagnostic — look for them early.",
        "Rash": "Appears day 3–5 after fever, starting at the hairline and behind the ears, then spreading downward across the face, neck, trunk, and limbs in a classic head-to-toe progression. Red, slightly raised blotches that merge into large patches. Unlike chickenpox: it does not blister and is not itchy. Unlike dengue: it progresses head-to-toe.",
    },
    "Scabies": {
        "Severe itching": "Intense, relentless itching — the hallmark. It is caused by an allergic reaction to the mite, its eggs, and waste. So severe it disrupts sleep and dominates the person's existence.",
        "Burrow tracks": "Thin, grey or skin-coloured wavy lines (3–10mm long) on the skin surface — the tunnels dug by burrowing mites. Most visible between fingers, on wrists, around the waist, genitals, and ankles. These tracks are diagnostic and absent in other itchy conditions.",
        "Rash": "Tiny red bumps and blisters scattered around burrow tracks and in skin folds — the body's allergic reaction.",
        "Skin sores": "Open sores and crusted areas from scratching, which can become secondarily infected.",
        "Night itching": "The itching becomes dramatically worse at night when warmth of the bed activates the mites — a distinguishing feature from other itchy rashes.",
    },
    "Diabetes Mellitus": {
        "Increased thirst": "Unquenchable thirst persisting despite drinking large amounts — the kidneys draw extra water to flush out excess glucose, leaving the body perpetually dehydrated.",
        "Frequent urination": "Unusually frequent, large-volume urination including waking at night multiple times. The urine may attract ants due to its sugar content — a traditional diagnostic clue.",
        "Fatigue": "Persistent tiredness and lack of energy because cells cannot use glucose efficiently for fuel despite high blood sugar.",
        "Blurred vision": "Fluctuating blurry vision caused by fluid shifts in the eye lens as blood sugar levels change.",
        "Slow-healing sores": "Cuts, blisters, or ulcers — especially on the feet — that take weeks or months to heal, or fail to heal entirely, due to poor circulation and reduced immunity.",
    },
    "Hypertension": {
        "Headache": "Usually a dull throbbing headache at the back of the head, often on waking. However, most hypertension causes no symptoms at all — it is frequently completely silent until a complication occurs.",
        "Dizziness": "Lightheadedness or imbalance, particularly when standing up suddenly.",
        "Blurred vision": "Visual disturbances or temporary loss of vision when blood pressure rises very high, from retinal vessel damage.",
        "Chest pain": "A heavy pressure in the chest if the heart is under excessive strain from persistent high pressure.",
        "Shortness of breath": "Difficulty breathing — particularly lying flat — if the heart begins to fail under the load.",
    },
    "Iron Deficiency Anemia": {
        "Fatigue": "Persistent, severe tiredness disproportionate to activity — exhausted even after rest, because the blood is carrying less oxygen to every organ and muscle.",
        "Pale skin": "Noticeable pallor of the skin, inner lower eyelid (pull down to see), gums, and nail beds — all appear lighter or whitish instead of their normal pinkish-red.",
        "Dizziness": "Lightheadedness and near-fainting, especially when standing, climbing stairs, or exerting.",
        "Shortness of breath": "Breathlessness with mild exertion — walking a short distance — because the blood cannot carry enough oxygen to meet demand.",
        "Fast heartbeat": "A racing or pounding heartbeat (palpitations) as the heart pumps faster to compensate for the oxygen deficit.",
    },
    "Cystitis UTI": {
        "Frequent urination": "An urgent, frequent need to urinate — going every few minutes — but passing only a small amount each time.",
        "Painful urination": "A burning or stinging sensation during urination (dysuria), often described as 'like passing razors'. Unlike kidney stones, the pain is during urination, not before.",
        "Pelvic pain": "A dull ache or pressure low in the pelvis, above the pubic bone.",
        "Blood in urine": "Urine appearing pink, red, or brownish from bleeding caused by bladder wall inflammation — requires medical evaluation.",
        "Lower abdominal pain": "Cramping or discomfort in the lower abdomen, especially when the bladder is full.",
    },
    "Helicobacteriosis PepticUlcer": {
        "Burning stomach pain": "A gnawing, burning pain in the upper central abdomen (epigastrium) occurring 1–3 hours after meals or when the stomach is empty — typically relieved briefly by eating or antacids, then returning.",
        "Nausea": "Persistent queasy feeling, especially in the morning or when the stomach is empty.",
        "Bloating": "A feeling of fullness or distension in the upper abdomen even after small meals.",
        "Heartburn": "A burning sensation rising from the stomach up into the chest and throat.",
        "Loss of appetite": "Reduced desire to eat, often from fear of pain after meals.",
    },
    "Common Cold": {
        "Runny nose": "Clear, watery nasal discharge in the first 1–3 days that may become thicker and yellower as the cold progresses — this colour change does not necessarily mean bacterial infection.",
        "Sore throat": "Scratchiness and mild pain at the back of the throat, usually worst on the first 1–2 days.",
        "Cough": "Initially dry and tickly, becoming productive later. Milder than pneumonia or TB cough — does not persist for weeks.",
        "Sneezing": "Frequent sneezing, particularly in the first 1–2 days.",
        "Mild fever": "Low-grade fever (37.2–38°C) if present at all. High fever in an adult is more suggestive of influenza.",
        "Headache": "Mild, generalised headache from nasal congestion and sinus pressure.",
    },
    "Skin Fungal Infection": {
        "Itchy skin": "Moderate to intense itching in the affected area, worsening in warm, sweaty conditions.",
        "Ring-shaped rash": "Circular red patches with a slightly raised, scaly, advancing border and clearer skin in the centre — the classic appearance. Distinctly different from the linear burrow tracks of scabies or the fluid blisters of chickenpox.",
        "Red scaly skin": "Reddened, flaking skin in body folds (groin, armpits, between toes) that may crack and weep.",
        "Skin peeling": "Flaking or peeling skin, especially between the toes in athlete's foot.",
        "Skin lesions": "Patches of discoloured skin — lighter or darker than surrounding skin, as in pityriasis versicolor.",
    },
    "Hepatitis A": {
        "Jaundice": "Yellowing of the skin and whites of the eyes (sclera), appearing 1–2 weeks after other symptoms. The yellow colour deepens over days, then slowly fades.",
        "Fatigue": "Profound exhaustion often appearing before jaundice — one of the earliest signs.",
        "Nausea": "Persistent queasiness and aversion to food and alcohol, often lasting weeks.",
        "Vomiting": "Frequent vomiting in the acute phase.",
        "Abdominal pain": "Dull aching pain in the upper right abdomen, directly over the liver.",
        "Dark urine": "Urine turns dark brown (like dark tea or cola) before skin jaundice becomes visible — an important early warning sign to recognise.",
        "Loss of appetite": "Total loss of interest in food, persisting for weeks.",
        "Fever": "Mild to moderate fever in the pre-jaundice phase.",
    },
    "Hepatitis B": {
        "Jaundice": "Yellow discolouration of skin and eyes, varying from mild to deep yellow depending on liver inflammation.",
        "Dark urine": "Deep amber or brown urine, appearing as the liver fails to process bilirubin.",
        "Fatigue": "Severe, prolonged fatigue that may persist for months in chronic infection.",
        "Yellow eyes": "The white part of the eyes (sclera) turns distinctly yellow — often the most visible sign.",
        "Abdominal pain": "Discomfort and tenderness in the upper right abdomen, directly over the liver.",
        "Joint pain": "Aching joints — particularly in early acute infection — sometimes appearing before jaundice.",
        "Loss of appetite": "Near-total loss of appetite that may cause significant weight loss.",
        "Nausea": "Persistent nausea and feeling sick at the smell or thought of food.",
    },
    "Yellow Fever": {
        "High fever": "Sudden onset of high fever (38.5–40°C) with an apparent improvement around day 3–4 (the 'period of remission') — this is deceptive, as a toxic phase with organ failure may follow.",
        "Jaundice": "Yellowing of skin and eyes from liver damage — the defining sign that gives the disease its name. Appears around day 4–5.",
        "Muscle aches": "Severe muscle pain, especially in the back and legs.",
        "Severe headache": "Intense frontal headache from the onset.",
        "Nausea": "Severe nausea, often with vomiting.",
        "Vomiting": "'Black vomit' — dark, coffee-ground-like material from internal bleeding — is a severe sign indicating liver and kidney failure, distinct from other causes of vomiting.",
        "Back pain": "Prominent back pain from the early phase.",
        "Yellow eyes": "The sclera turns deeply yellow from bilirubin accumulation.",
    },
    "Whooping Cough": {
        "Cough": "Begins as an ordinary cough for 1–2 weeks, then develops into violent, uncontrollable coughing fits: 5–10 rapid coughs in a single breath, followed by the characteristic high-pitched 'whoop' as the person gasps for air. The fits can last a minute, turn the face red or blue, and often end in vomiting. This pattern is highly distinctive.",
        "Runny nose": "Watery nasal discharge in the early cold-like stage before severe coughing begins.",
        "Fever": "Usually low-grade or absent — the violent cough, not fever, distinguishes this illness.",
        "Sneezing": "Present in the early stage.",
        "Vomiting": "Coughing fits are often severe enough to trigger vomiting, particularly in children.",
        "Fatigue": "Exhaustion from the physical effort of repeated coughing fits throughout the day and night.",
        "Weakness": "Progressive weakness as the illness continues for weeks.",
    },
    "Mumps": {
        "Swollen lymph nodes": "Swelling of the parotid salivary glands in front of and below the ears causes the characteristic 'chipmunk cheeks' or 'hamster face' appearance. One or both sides may be affected. This is unique to mumps among common infections.",
        "Jaw stiffness": "Pain and stiffness when opening the mouth or chewing, due to the swollen glands pressing on the jaw.",
        "Fever": "Moderate fever (38–39°C) from the start.",
        "Headache": "Generalised headache accompanying the fever.",
        "Muscle aches": "Mild to moderate muscle aching.",
        "Fatigue": "Tiredness and malaise throughout the illness.",
        "Loss of appetite": "Reduced desire to eat, partly because chewing is painful.",
    },
    "Rubella": {
        "Mild fever": "Low-grade fever (37.2–38°C), usually appearing before the rash.",
        "Rash": "Fine, flat pink-to-red spots (macules) beginning on the face then spreading down the neck, trunk, and limbs over 24 hours. The face clears as the trunk rash appears. Lighter and shorter-lived (2–3 days) than measles; does not blister like chickenpox.",
        "Swollen lymph nodes": "Tender, swollen lymph nodes behind the ears, at the back of the neck, and behind the head — a characteristic feature that may appear before the rash and persist after.",
        "Red eyes": "Mild redness and watering of the eyes.",
        "Runny nose": "Mild nasal congestion or discharge.",
        "Joint pain": "Aching joints, especially fingers and wrists — more common and noticeable in adult women.",
        "Headache": "Mild, diffuse headache.",
    },
    "Sinusitis": {
        "Headache": "Pressure and pain across the forehead, cheeks, and around the eyes. Bending forward dramatically worsens the pain — a useful distinguishing feature from tension headache.",
        "Nasal congestion": "Blocked, stuffy nose making breathing through the nose difficult or impossible.",
        "Facial pain": "Tenderness and pressure when pressing over the cheekbones and forehead, directly over the sinus cavities.",
        "Runny nose": "Thick, coloured (yellow or green) nasal discharge that may drip down the back of the throat (postnasal drip).",
        "Cough": "Persistent cough from postnasal drip — mucus draining down the throat, worsening when lying down at night.",
        "Sore throat": "Irritation at the back of the throat from dripping mucus.",
        "Fever": "Low-grade fever if bacterial infection is present.",
    },
    "Tonsillitis": {
        "Sore throat": "Severe throat pain — often among the worst the person has experienced — making swallowing extremely painful. The tonsils appear enlarged, red, and often coated with white or yellow patches of pus.",
        "Difficulty swallowing": "Pain on swallowing even saliva. The person may drool, refuse liquids, or have a muffled 'hot potato' voice.",
        "Swollen lymph nodes": "Tender, enlarged lymph nodes on both sides of the neck, easily felt and visible.",
        "High fever": "High fever (38.5–40°C), often with chills.",
        "Headache": "Headache accompanying the fever.",
        "Fatigue": "Significant tiredness and malaise.",
        "Loss of appetite": "Refusal to eat because swallowing is too painful.",
    },
    "Ear Infection": {
        "Ear pain": "Sharp, stabbing, or throbbing pain inside the ear, which may be continuous or wave-like. In young children, they may tug at the ear or be unusually irritable without being able to describe the pain.",
        "Fever": "Moderate fever accompanying the ear pain.",
        "Hearing loss": "Reduced hearing or a muffled, blocked feeling in the ear from fluid buildup behind the eardrum.",
        "Headache": "Generalised headache from the infection and fever.",
        "Dizziness": "Sense of imbalance or spinning, if the inner ear is involved.",
        "Fatigue": "Tiredness accompanying the illness.",
        "Pus or discharge": "Yellow, white, or bloody fluid draining from the ear if the eardrum has ruptured — this often suddenly relieves the severe pain.",
    },
    "Conjunctivitis": {
        "Red eyes": "The white of the eye (sclera) turns bright red or pink from inflammation. Both eyes are often affected.",
        "Eye discharge": "Sticky, crusting discharge from the eye. Bacterial: thick, yellow-green — causes eyelids to seal shut on waking. Viral: watery. Allergic: stringy or ropy. The type of discharge helps identify the cause.",
        "Itchy skin": "Intense itching and a gritty or sandy sensation in the eye, particularly in allergic conjunctivitis.",
        "Eye pain": "Mild discomfort or burning — severe pain suggests a more serious eye condition.",
        "Sensitivity to light": "Mild discomfort in bright light.",
        "Headache": "Mild headache from eye strain and inflammation.",
    },
    "Herpes Zoster": {
        "Blisters": "Small, fluid-filled blisters appearing in a band or strip along one nerve pathway on one side of the body — never crossing the midline. This strict one-sided distribution is diagnostic. The blisters break, weep, and crust over in 7–10 days.",
        "Rash": "Red, inflamed skin appears 2–3 days before the blisters form, strictly following the path of one nerve — a stripe on the chest, back, face, or limb.",
        "Itchy rash": "Intense itching and tingling in the affected area, often beginning days before any visible rash or blisters appear.",
        "Fever": "Mild fever at onset.",
        "Fatigue": "Tiredness and general malaise throughout the illness.",
        "Headache": "Headache, particularly if the rash involves the head or face.",
        "Sensitivity to light": "Light sensitivity if the rash involves the eye area.",
        "Skin sores": "Open, weeping sores as blisters rupture — can become secondarily infected if scratched.",
    },
    "Appendicitis": {
        "Abdominal pain": "Classically begins as vague, cramping pain around the navel, then over 12–24 hours shifts and concentrates in the lower right abdomen. It becomes constant, worsening with movement, coughing, or pressing then suddenly releasing the area (rebound tenderness). This migration of pain is highly characteristic.",
        "Fever": "Low-grade fever initially (37.5–38.5°C), rising if the appendix ruptures.",
        "Nausea": "Nausea that accompanies the onset of pain.",
        "Vomiting": "One or two episodes of vomiting after the pain begins — not usually repeated.",
        "Loss of appetite": "Complete loss of appetite from the onset.",
        "Weakness": "General malaise and weakness.",
        "Constipation": "Reduced or absent bowel movement due to pain and inflammation.",
    },
    "Kidney Stones": {
        "Back pain": "Sudden, excruciating, wave-like (colicky) pain in the back, flank, or below the ribs on one side, radiating downward toward the groin as the stone moves. One of the most severe pains a person can experience — they cannot find a comfortable position.",
        "Blood in urine": "Urine appears pink, red, or dark brown from the stone scratching the urinary tract lining.",
        "Painful urination": "Burning or stinging when urinating as the stone nears the bladder or urethra.",
        "Nausea": "Severe nausea accompanying the pain, from shared nerve pathways between the ureter and intestines.",
        "Vomiting": "May accompany severe pain episodes.",
        "Frequent urination": "Urgent need to urinate frequently when the stone is in the lower ureter near the bladder.",
        "Lower abdominal pain": "Pain moving into the lower abdomen and groin as the stone descends.",
    },
    "Sickle Cell Crisis": {
        "Joint pain": "Severe, deep, throbbing pain in bones and joints — chest, back, hips, and long bones. Caused by sickled cells blocking blood vessels (vaso-occlusive crisis). The pain is often more intense than any other pain the person has experienced.",
        "Fatigue": "Chronic, severe tiredness from anaemia — sickled red blood cells break down faster than normal ones.",
        "Pale skin": "Pallor of the skin, mucous membranes, and conjunctiva from anaemia.",
        "Chest pain": "Acute chest syndrome — chest pain with breathing difficulty — is a serious complication requiring urgent hospital care.",
        "Shortness of breath": "Difficulty breathing from acute chest syndrome or severe anaemia.",
        "Jaundice": "Yellowing of the eyes and skin from breakdown products of destroyed red blood cells.",
        "Swollen feet": "Painful swelling of hands and feet (dactylitis), particularly in young children — often the very first sign of the disease.",
    },
    "Tetanus": {
        "Jaw stiffness": "The first and most characteristic symptom — jaw muscles clamp shut (lockjaw/trismus), making it impossible to fully open the mouth. This develops 3–21 days after a wound and progresses to affect other muscles.",
        "Stiff neck": "Neck muscle rigidity follows the jaw stiffness as the toxin spreads.",
        "Muscle cramps": "Painful, generalised muscle spasms throughout the body. The back may arch violently (opisthotonus). Any stimulus — noise, light, or touch — can trigger a life-threatening whole-body spasm.",
        "Fever": "Moderate fever from muscle activity and the underlying infection.",
        "Headache": "Headache accompanying the muscular tension.",
        "Difficulty swallowing": "Difficulty swallowing from throat muscle rigidity.",
        "Sweating": "Profuse sweating from muscle spasms and autonomic nervous system involvement.",
    },
    "Diphtheria": {
        "Sore throat": "Sore throat with a thick, grey-white membrane coating the tonsils and back of the throat that bleeds when disturbed — unlike the removable white patches of tonsillitis. This membrane is diagnostic.",
        "Hoarse voice": "Hoarseness and a barking or stridor-like quality to the voice from airway involvement.",
        "Difficulty swallowing": "Throat membrane and swelling make swallowing painful.",
        "Fever": "Moderate fever — generally lower than other severe throat infections.",
        "Swollen lymph nodes": "Enlarged lymph nodes in the neck cause the 'bull neck' appearance.",
        "Fatigue": "Significant toxaemia from the bacterial toxin — the person appears ill beyond what the fever would suggest.",
        "Runny nose": "Blood-stained nasal discharge in some forms of the disease.",
    },
    "Ringworm": {
        "Ring-shaped rash": "Circular, red, scaly patches with a raised, active, advancing edge and a clearing centre — the 'ring' appearance. Multiple overlapping rings may form. Unlike HIV rash (flat, central) or chickenpox (blistered), this is distinctly circular and expanding.",
        "Itchy skin": "Persistent itching at the advancing edge of the ring, where the fungus is most active.",
        "Red scaly skin": "Redness and fine scaling inside and around the rings.",
        "Skin peeling": "Fine, powdery or sheet-like peeling at lesion edges.",
        "Skin lesions": "In scalp ringworm (tinea capitis): patchy hair loss with broken hairs and scaling — may look like dandruff with bald spots.",
        "Hair loss": "In scalp involvement, hair breaks off close to the root, leaving short stubs and bald patches — a distinctive sign.",
    },
    "Leptospirosis": {
        "High fever": "Sudden onset of high fever (38.5–40°C) with severe chills.",
        "Muscle aches": "Severe muscle pain especially in the calves and thighs — so intense that walking is difficult. This pronounced calf tenderness is a key distinguishing feature.",
        "Headache": "Intense headache, often felt behind the eyes.",
        "Red eyes": "Conjunctival suffusion — the whites of the eyes become red and bloodshot without discharge — a characteristic early finding distinct from conjunctivitis.",
        "Jaundice": "In severe leptospirosis (Weil's disease), jaundice appears after 4–7 days from liver involvement.",
        "Vomiting": "Nausea and vomiting accompanying the fever.",
        "Rash": "A transient rash may appear, though less prominent than in dengue.",
        "Dark urine": "Dark urine from kidney or liver involvement — a warning sign of severe disease.",
    },
    "Typhus": {
        "Sudden high fever": "Abrupt onset of very high fever (39–40°C) with rigors, lasting 2 weeks if untreated.",
        "Severe headache": "Intense, debilitating headache from the start — one of the most prominent features.",
        "Rash": "Appears around day 4–6, starting on the trunk and spreading to the limbs (typically sparing the face, palms, and soles). Small, flat pink or red spots that may darken and become purplish. Unlike measles (head-to-toe), typhus rash begins on the trunk. Unlike dengue, it persists longer.",
        "Muscle aches": "Severe, generalised muscle pain.",
        "Fatigue": "Extreme weakness and prostration.",
        "Confusion": "Confusion or altered consciousness in severe cases — the word 'typhus' comes from Greek for 'smoke', referring to this mental clouding.",
        "Chills": "Violent shaking chills at fever onset.",
    },
    "Brucellosis": {
        "Fever": "An undulating (wave-like) fever that rises and falls in a regular pattern, sometimes cycling over weeks — often worse in the evenings. This undulating pattern distinguishes it from most other fevers.",
        "Sweating": "Profuse sweating, especially at night, with a characteristic musty odour — a classic though uncommon feature.",
        "Joint pain": "Aching joints, especially large joints — hips, knees, sacroiliac joints — and the spine.",
        "Muscle aches": "Widespread muscle pain and weakness.",
        "Fatigue": "Profound, debilitating fatigue persisting even between fever episodes.",
        "Loss of appetite": "Reduced appetite and progressive weight loss.",
        "Back pain": "Low back pain from spinal involvement (spondylitis), a common complication of untreated brucellosis.",
        "Night sweats": "Heavy sweating during sleep, often soaking bedding.",
    },
    "Septicemia": {
        "High fever": "Very high fever or, paradoxically, abnormally low temperature (below 36°C) in severe cases — both indicate systemic infection. The temperature extremes are alarming.",
        "Confusion": "Sudden confusion, agitation, or altered consciousness — a critical warning sign indicating inadequate oxygen supply to the brain.",
        "Fast heartbeat": "Rapid heart rate (>90 beats/min) as the body tries to compensate for falling blood pressure.",
        "Shortness of breath": "Rapid breathing (>20 breaths/min) as the body attempts to correct acid-base imbalance from poor circulation.",
        "Low blood pressure": "Blood pressure drops dramatically — the person becomes cold, clammy, and may collapse. Septic shock is immediately life-threatening.",
        "Chills": "Violent shivering with the onset of fever.",
        "Sweating": "Cold, clammy skin and drenching sweat as blood pressure falls.",
    },
    "Pelvic Inflammatory Disease": {
        "Pelvic pain": "Dull, constant pain low in the abdomen, usually on both sides. May worsen during intercourse (dyspareunia), menstruation, or urination.",
        "Vaginal discharge": "Abnormal vaginal discharge — often yellow or green with an unpleasant odour — indicating active infection of the cervix and uterus.",
        "Lower abdominal pain": "Cramping lower abdominal pain that may be mild initially and gradually worsen over days.",
        "Fever": "Fever above 38°C, sometimes with chills.",
        "Painful urination": "Burning on urination if the bladder or urethra is also irritated.",
        "Missed period": "Irregular or missed periods from the infection's effect on reproductive structures.",
    },
    "Benign Prostatic Hyperplasia": {
        "Frequent urination": "Need to urinate very often, including waking multiple times at night (nocturia), even when only small amounts of urine are produced.",
        "Reduced urination": "Weak, slow, or intermittent urine stream — may start and stop, dribble at the end, require straining. The person feels the bladder is never fully empty.",
        "Sleep disturbances": "Repeated night waking to urinate, significantly disrupting sleep quality.",
        "Lower abdominal pain": "A dull sense of pressure or fullness above the pubic bone from incomplete bladder emptying.",
        "Weakness": "General fatigue from sleep disruption and potentially from kidney effects.",
        "Back pain": "Mild back or flank pain if the condition causes kidney pressure.",
    },
    "Migraine": {
        "Severe headache": "Intense, pulsating or throbbing pain — usually on one side of the head. Worsened by physical activity, light, sound, and smell. Lasts 4–72 hours without treatment. Distinguishable from tension headache by its severity, one-sidedness, and accompanying symptoms.",
        "Sensitivity to light": "Extreme pain discomfort in bright light (photophobia) — the person must go to a dark room and may be unable to function.",
        "Sensitivity to sound": "Ordinary sounds feel unbearably loud and worsen the headache.",
        "Nausea": "Persistent nausea making it impossible to eat or drink during an attack.",
        "Vomiting": "Occurs in many attacks — may temporarily relieve the headache in some people.",
        "Blurred vision": "Visual aura preceding the headache: zigzag patterns, flashing lights, blind spots, or tunnel vision, lasting 20–60 minutes. These visual disturbances before the pain are diagnostic of migraine with aura.",
        "Dizziness": "Vertigo or dizziness may accompany, particularly in vestibular migraine.",
    },
    "Epilepsy": {
        "Seizures": "Episodes of abnormal electrical brain activity ranging from brief staring spells (absence seizures) to full convulsions: stiff muscles → rhythmic jerking of the whole body → unconsciousness → possible loss of bladder control. Each episode is usually 1–3 minutes.",
        "Confusion": "A period of confusion and disorientation immediately after a seizure (postictal state), lasting minutes to hours — the person has no memory of the event.",
        "Confusion at night": "Nocturnal seizures may cause the person to wake confused and disoriented, often without realising a seizure occurred.",
        "Muscle cramps": "Involuntary muscle jerking or stiffening during the seizure.",
        "Fatigue": "Severe exhaustion following a seizure — sometimes lasting a full day — as the brain recovers.",
        "Weakness": "Weakness or temporary paralysis on one side of the body after a seizure (Todd's paralysis), lasting minutes to hours.",
        "Poor coordination": "Unsteady walking or clumsiness following a seizure, or as a persistent feature in some seizure types.",
    },
    "Onchocerciasis": {
        "Severe itching": "Intense, relentless whole-body itching among the most severe of any disease — caused by the immune response to dying microfilariae in the skin. Continuous scratching leads to thickened, scarred skin.",
        "Skin lesions": "Chronic skin changes: depigmentation (loss of colour, creating a 'leopard skin' pattern of pale and dark patches), wrinkling and thickening, and firm nodules under the skin where adult worms live.",
        "Blurred vision": "Progressive visual impairment from microfilariae invading the eye. Untreated, leads to corneal scarring and permanent blindness — known as 'river blindness'.",
        "Rash": "Papular rash and raised bumps from skin microfilariae, particularly on the torso and thighs.",
        "Skin peeling": "Dry, rough, peeling skin in chronic infection.",
        "Swollen lymph nodes": "Enlarged lymph nodes in the groin from the immune response.",
        "Weight loss": "Progressive weight loss and wasting in long-standing infection.",
    },
    "Filariasis": {
        "Swollen feet": "Massive, firm swelling of the legs, feet, or genitals (lymphoedema) from long-standing lymphatic blockage. The skin becomes thick, rough, and warty — a condition called elephantiasis. This level of swelling is unique to filariasis and lymphatic obstruction.",
        "Ankle swelling": "Pitting oedema of the ankles and lower legs in early stages, before elephantiasis develops.",
        "Skin lesions": "Thickened, folded, rough skin over swollen areas.",
        "Fever": "Episodic fever with chills during acute lymphangitis attacks, when bacteria invade the damaged lymphatics.",
        "Skin sores": "Ulcers and sores on swollen skin, prone to infection.",
        "Weakness": "Fatigue and weakness during fever episodes.",
        "Itchy skin": "Itching of the swollen, thickened skin.",
    },
    "HIV AIDS": {
        "Fatigue": "Profound, persistent tiredness not improved by rest — the immune system works continuously, and opportunistic infections drain energy. In AIDS, fatigue can be completely debilitating.",
        "Weight loss": "Unintentional loss of >10% of body weight combined with diarrhoea or fever for more than 30 days — HIV wasting syndrome. Unlike dieting, the weight loss is accompanied by illness.",
        "Night sweats": "Drenching sweats during sleep soaking the bedding and clothing, even without fever — a hallmark symptom of HIV and certain other infections.",
        "Swollen lymph nodes": "Persistent swelling of lymph nodes in the neck, armpits, and groin lasting more than 3 months without obvious infection — persistent generalised lymphadenopathy. Helps distinguish HIV from a short-term infection.",
        "Diarrhea": "Chronic or recurrent watery diarrhoea from gut opportunistic infections (e.g., cryptosporidium, CMV) that persist for weeks and contribute to weight loss.",
        "Fever": "Recurrent low-grade fevers from immune activation and opportunistic infections.",
        "Rash": "In acute HIV infection (2–4 weeks after exposure): flat, reddish-pink spots (maculopapular rash) mainly on the trunk, face, and arms — not itchy, non-blistering, lasting 1–2 weeks. Distinctly different from: chickenpox (intensely itchy, blistered), dengue (white islands in red sea), measles (head-to-toe spread with cough/runny nose).",
        "Loss of appetite": "Reduced appetite and nausea, worsened by oral thrush (white patches in the mouth) or oesophageal infections.",
        "Cough": "Persistent dry or productive cough from Pneumocystis pneumonia (PCP) or TB — both common in AIDS.",
        "Sore throat": "Recurring throat pain from oral candidiasis (thrush) — white patches on the tongue and inner cheeks.",
    },
    "Skin Abscess": {
        "Skin sores": "A painful, tender, raised lump under the skin filled with pus. The skin over it is red, warm, and tense. As it matures, the centre becomes soft and may develop a yellow-white 'head' (pointing). This is visually distinct from a rash or ring lesion.",
        "Pus or discharge": "Thick, creamy, yellow or yellow-green pus that drains when the abscess is lanced or ruptures spontaneously.",
        "Rash": "Surrounding redness and warmth (cellulitis) spreading outward from the abscess — different from the dry, scaly rings of ringworm or the blistered pattern of chickenpox.",
        "Fever": "Fever if the infection is spreading beyond the abscess.",
        "Fatigue": "Tiredness from the immune response.",
        "Swollen lymph nodes": "Tender swollen lymph nodes in the region draining the abscess (e.g., armpit nodes for a hand abscess).",
    },
    "Anaphylaxis": {
        "Rash": "Sudden onset of widespread hives (urticaria) — raised, itchy, red welts of varying sizes — or generalised flushing. Appears within minutes of exposure to the trigger. The speed of onset distinguishes it from other rashes.",
        "Shortness of breath": "Severe difficulty breathing from swelling of the airway (throat and vocal cords) and bronchospasm. The person may be unable to speak a full sentence — life-threatening within minutes.",
        "Fast heartbeat": "Rapid, weak pulse as the heart races to compensate for falling blood pressure.",
        "Dizziness": "Lightheadedness and near-fainting from sudden blood pressure drop.",
        "Low blood pressure": "Dramatic, rapid fall in blood pressure causing pallor, weakness, and collapse — anaphylactic shock.",
        "Nausea": "Sudden nausea and cramping abdominal pain.",
        "Swollen feet": "Swelling of the face, lips, tongue, and throat (angioedema) — throat swelling is immediately life-threatening.",
        "Sweating": "Pale, cold, clammy skin with profuse sweating as the body goes into shock.",
    },
}


def slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def _load_json(path: str):
    file_path = Path(path)
    if file_path.exists():
        return json.loads(file_path.read_text(encoding="utf-8"))
    return None


def _normalize_disease(raw: dict) -> dict:
    name = raw.get("name") or raw.get("disease") or "Unknown Disease"
    curated = CURATED_DETAILS.get(name, {})
    raw_sections = raw.get("sections") or {}
    sections = {
        "Overview": curated["description"],
        "Causes": curated["causes"],
        "Treatment": curated["treatment"],
        "Prevention": "\n".join(curated["prevention"]),
    } if curated else raw_sections
    description = (
        curated.get("description")
        or raw.get("description")
        or sections.get("Description")
        or sections.get("Definition")
        or ""
    )
    symptoms = raw.get("symptoms") or CORE_SYMPTOMS.get(name) or []

    HIGH_SEVERITY = {
        "Malaria", "Typhoid Fever", "Cholera", "Pneumonia", "Tuberculosis",
        "Meningitis", "Dengue Fever", "Yellow Fever", "Hepatitis B", "Whooping Cough",
        "Tetanus", "Diphtheria", "Leptospirosis", "Typhus", "Septicemia",
        "Sickle Cell Crisis", "Appendicitis", "Kidney Stones", "Epilepsy",
        "Onchocerciasis", "Filariasis", "HIV AIDS", "Anaphylaxis",
        "Pelvic Inflammatory Disease",
    }
    severity = raw.get("severity") or ("High" if name in HIGH_SEVERITY else "Medium")

    FEATURED = {"Malaria", "Typhoid Fever", "Cholera", "Pneumonia", "HIV AIDS", "Tuberculosis"}

    return {
        "id": raw.get("id") or slugify(name),
        "slug": raw.get("slug") or slugify(name),
        "name": name,
        "disease": name,
        "category": raw.get("category") or CATEGORIES.get(name, "General"),
        "featured": raw.get("featured", name in FEATURED),
        "severity": severity,
        "symptoms": symptoms,
        "description": description[:600] if description else f"Encyclopedia information for {name}.",
        "causes": curated.get("causes") or raw.get("causes") or sections.get("Causes and symptoms") or sections.get("Causes") or "",
        "treatment": curated.get("treatment") or raw.get("treatment") or sections.get("Treatment") or "",
        "prevention": curated.get("prevention") or raw.get("prevention") or [sections.get("Prevention", "")],
        "sections": sections,
        "genderSpecific": curated.get("genderSpecific") or raw.get("genderSpecific"),
        "symptom_descriptions": SYMPTOM_DESCRIPTIONS.get(name, {}),
    }


FALLBACK_DISEASES = [_normalize_disease({"disease": name}) for name in CORE_SYMPTOMS]
_structured = _load_json("data_pipeline/mediguard_structured.json")

if _structured:
    # Merge structured JSON with any new diseases not yet in JSON
    existing_names = {item.get("name") or item.get("disease") for item in _structured}
    extra = [
        {"disease": name}
        for name in CORE_SYMPTOMS
        if name not in existing_names
    ]
    DISEASES = [_normalize_disease(item) for item in _structured + extra]
else:
    DISEASES = FALLBACK_DISEASES

SYMPTOMS = (
    _load_json("data_pipeline/symptoms_list.json")
    or sorted({symptom for disease in DISEASES for symptom in disease["symptoms"]})
)
