#!/usr/bin/env python3
"""
add_curated_disease_data.py
============================
Adds medically-accurate curated symptom rows for diseases that still have
very few samples after the dhivyeshrk import.

Each disease profile is defined by:
  - ALWAYS symptoms  (present in virtually all cases)
  - COMMON symptoms  (present in ~60-80% of cases)
  - OCCASIONAL symptoms (present in ~20-40% of cases)
  - RARE symptoms (present in ~5-15% of cases)

Rows are generated by sampling from these probability-weighted profiles with
controlled randomness, producing diverse but medically plausible rows.

Usage:
    cd mediguard-backend
    python scripts/add_curated_disease_data.py

Outputs updated:
    data/raw/mediguard_dataset_full.csv
"""

import json
import random
import sys
from pathlib import Path

import pandas as pd

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

random.seed(42)

BASE       = Path(__file__).parent.parent
TARGET_CSV = BASE / "data/raw/mediguard_dataset_full.csv"
SYMS_JSON  = BASE / "models/symptoms_list.json"

# ── Disease symptom profiles (evidence-based) ──────────────────────────────────
# Each entry: {"always": [...], "common": [...], "occasional": [...], "rare": [...]}
# probabilities: always=1.0, common=0.70, occasional=0.35, rare=0.10

DISEASE_PROFILES: dict[str, dict] = {

    "Measles": {
        "always":     ["Fever", "Rash", "Cough", "Red eyes"],
        "common":     ["Koplik spots", "Runny nose", "High fever", "Sensitivity to light",
                       "Loss of appetite", "Fatigue", "Sneezing", "Body aches"],
        "occasional": ["Headache", "Vomiting", "Sore throat", "Swollen lymph nodes",
                       "Eye discharge", "Mild fever"],
        "rare":       ["Seizures", "Confusion", "Ear pain", "Diarrhea"],
        "count": 120,
    },

    "Rubella": {
        "always":     ["Rash", "Mild fever"],
        "common":     ["Swollen lymph nodes", "Runny nose", "Headache", "Joint pain",
                       "Red eyes", "Fatigue", "Loss of appetite"],
        "occasional": ["Cough", "Sneezing", "Body aches", "Eye discharge",
                       "Neck pain", "Itchy skin"],
        "rare":       ["Vomiting", "Sore throat", "Sensitivity to light"],
        "count": 120,
    },

    "Tetanus": {
        "always":     ["Jaw stiffness", "Muscle cramps", "Stiffness"],
        "common":     ["Difficulty swallowing", "Fever", "Sweating", "High fever",
                       "Neck pain", "Body aches"],
        "occasional": ["Headache", "Sore throat", "Irritability", "Seizures",
                       "Shortness of breath", "Muscle aches"],
        "rare":       ["Confusion", "Fast heartbeat", "Vomiting", "Weakness"],
        "count": 120,
    },

    "Rabies": {
        "always":     ["Hydrophobia", "Agitation", "Confusion"],
        "common":     ["Fever", "Headache", "Weakness", "Anxiety",
                       "Muscle aches", "Fatigue", "Numbness"],
        "occasional": ["Seizures", "Difficulty swallowing", "Muscle cramps",
                       "Sensitivity to light", "Stiffness", "Irritability"],
        "rare":       ["Vomiting", "Excessive sleepiness", "Loss of appetite",
                       "Sweating", "Fast heartbeat"],
        "count": 120,
    },

    "Epilepsy": {
        "always":     ["Seizures"],
        "common":     ["Confusion", "Loss of appetite", "Weakness", "Excessive sleepiness",
                       "Fatigue"],
        "occasional": ["Headache", "Anxiety", "Muscle cramps", "Numbness",
                       "Body aches", "Irritability", "Sleep disturbances"],
        "rare":       ["Nausea", "Vomiting", "Sensitivity to light", "Dizziness",
                       "Sensitivity to sound"],
        "count": 120,
    },

    "Gonorrhea": {
        "always":     ["Genital discharge"],
        "common":     ["Painful urination", "Pelvic pain", "Genital sores",
                       "Lower abdominal pain"],
        "occasional": ["Frequent urination", "Fever", "Swollen lymph nodes",
                       "Vaginal discharge", "Joint pain"],
        "rare":       ["Sore throat", "Eye discharge", "Red eyes", "Skin lesions",
                       "Fast heartbeat"],
        "count": 120,
    },

    "Mumps": {
        "always":     ["Jaw swelling"],
        "common":     ["Fever", "Headache", "Fatigue", "Loss of appetite",
                       "Muscle aches", "Swollen lymph nodes"],
        "occasional": ["Ear pain", "Sore throat", "Difficulty swallowing",
                       "Vomiting", "Abdominal pain"],
        "rare":       ["Seizures", "Sensitivity to light", "Stiff neck", "Confusion"],
        "count": 120,
    },

    "Herpes Zoster": {
        "always":     ["Blisters", "Rash"],
        "common":     ["Itchy skin", "Burning stomach pain", "Skin lesions",
                       "Fatigue", "Sensitivity to light", "Fever"],
        "occasional": ["Headache", "Chills", "Body aches", "Numbness",
                       "Eye pain", "Eye discharge", "Skin redness", "Skin warmth"],
        "rare":       ["Red eyes", "Hearing loss", "Weakness", "Facial pain",
                       "Facial drooping"],
        "count": 150,
    },

    "Hemorrhoids (Piles)": {
        "always":     ["Rectal bleeding", "Anal pain"],
        "common":     ["Anal itching", "Swelling near anus", "Pain during bowel movement",
                       "Blood in stool"],
        "occasional": ["Constipation", "Mucus discharge from anus", "Bloating",
                       "Lower abdominal pain"],
        "rare":       ["Fatigue", "Dizziness", "Pale skin"],
        "count": 150,
    },

    "Appendicitis": {
        "always":     ["Lower abdominal pain", "Abdominal pain"],
        "common":     ["Nausea", "Vomiting", "Fever", "Loss of appetite",
                       "Constipation", "Diarrhea"],
        "occasional": ["High fever", "Bloating", "Back pain", "Dizziness",
                       "Body aches", "Weakness"],
        "rare":       ["Chills", "Headache", "Frequent urination", "Painful urination"],
        "count": 150,
    },

    "Conjunctivitis": {
        "always":     ["Red eyes", "Eye discharge"],
        "common":     ["Itchy skin", "Sensitivity to light", "Eye pain",
                       "Blurred vision", "Watery eyes"],
        "occasional": ["Runny nose", "Sore throat", "Sneezing", "Headache",
                       "Fever", "Mild fever"],
        "rare":       ["Swollen lymph nodes", "Ear pain", "Fatigue"],
        "count": 150,
    },

    "Kidney Stones": {
        "always":     ["Back pain", "Blood in urine"],
        "common":     ["Nausea", "Vomiting", "Painful urination", "Lower abdominal pain",
                       "Frequent urination", "Pelvic pain"],
        "occasional": ["Fever", "Chills", "Dizziness", "Sweating",
                       "Reduced urination", "Body aches"],
        "rare":       ["Headache", "Weakness", "Loss of appetite"],
        "count": 150,
    },

    "Meningitis": {
        "always":     ["Severe headache", "Stiff neck", "High fever"],
        "common":     ["Sensitivity to light", "Confusion", "Nausea", "Vomiting",
                       "Fever", "Sensitivity to sound"],
        "occasional": ["Seizures", "Rash", "Body aches", "Fatigue",
                       "Neck pain", "Weakness", "Loss of appetite"],
        "rare":       ["Blurred vision", "Numbness", "Red eyes", "Dizziness"],
        "count": 150,
    },

    "Septicemia": {
        "always":     ["High fever", "Fast heartbeat"],
        "common":     ["Confusion", "Shortness of breath", "Low blood pressure",
                       "Chills", "Sweating", "Weakness"],
        "occasional": ["Nausea", "Vomiting", "Diarrhea", "Body aches",
                       "Fatigue", "Skin lesions", "Rash"],
        "rare":       ["Jaundice", "Blood in urine", "Reduced urination",
                       "Seizures", "Skin redness"],
        "count": 150,
    },

    "Iron Deficiency Anemia": {
        "always":     ["Fatigue", "Pale skin"],
        "common":     ["Weakness", "Shortness of breath", "Dizziness", "Fast heartbeat",
                       "Loss of appetite", "Headache"],
        "occasional": ["Cold intolerance", "Brittle nails", "Hair loss",
                       "Body aches", "Difficulty swallowing", "Sleep disturbances"],
        "rare":       ["Chest pain", "Numbness", "Anxiety", "Swollen feet"],
        "count": 150,
    },

    "Stroke": {
        "always":     ["Facial drooping", "Speech difficulty"],
        "common":     ["Weakness", "Numbness", "Severe headache", "Confusion",
                       "Loss of balance", "Blurred vision"],
        "occasional": ["Difficulty walking", "Poor coordination", "Dizziness",
                       "Nausea", "Vomiting", "Sensitivity to light"],
        "rare":       ["Seizures", "Headache", "Loss of taste", "Loss of smell",
                       "Fast heartbeat"],
        "count": 150,
    },

    "Tonsillitis": {
        "always":     ["Sore throat", "Difficulty swallowing"],
        "common":     ["Fever", "Swollen lymph nodes", "Headache", "Hoarse voice",
                       "Loss of appetite", "Ear pain"],
        "occasional": ["Cough", "Bad breath", "White patches in mouth", "Fatigue",
                       "Chills", "Body aches"],
        "rare":       ["Nausea", "Vomiting", "Abdominal pain", "Nasal congestion"],
        "count": 120,
    },
}

PROB_MAP = {
    "always": 1.00,
    "common": 0.70,
    "occasional": 0.35,
    "rare": 0.10,
}

# Also add slight random noise for uncommon symptoms outside the profile
NOISE_PROB = 0.03  # 3% chance any non-profile symptom is 1


def generate_row(disease: str, profile: dict, our_symptoms: list[str]) -> dict:
    row = {s: 0 for s in our_symptoms}
    row["disease"] = disease

    # Symptom profile
    for level, symptoms in profile.items():
        if level == "count":
            continue
        prob = PROB_MAP[level]
        for sym in symptoms:
            if sym in row:
                row[sym] = 1 if random.random() < prob else 0

    # Low-level noise for other symptoms
    profile_syms = set()
    for level, syms in profile.items():
        if level != "count":
            profile_syms.update(syms)
    for sym in our_symptoms:
        if sym not in profile_syms and random.random() < NOISE_PROB:
            row[sym] = 1

    return row


def main() -> None:
    if not TARGET_CSV.exists():
        print(f"ERROR: {TARGET_CSV} not found")
        sys.exit(1)

    our_symptoms = json.loads(SYMS_JSON.read_text(encoding="utf-8"))
    df_existing  = pd.read_csv(TARGET_CSV)
    existing_counts = df_existing["disease"].value_counts()

    print("Generating curated rows for weak diseases...")
    print(f"{'Disease':<40} {'Existing':>8}  {'Target':>6}  {'Will add':>8}")
    print("-" * 70)

    all_new_rows = []
    for disease, profile in DISEASE_PROFILES.items():
        target = profile["count"]
        existing = existing_counts.get(disease, 0)
        # Only generate rows if we still need them (existing < target)
        n_to_add = max(0, target - existing)
        print(f"  {disease:<40} {existing:>8}  {target:>6}  {n_to_add:>8}")
        for _ in range(n_to_add):
            all_new_rows.append(generate_row(disease, profile, our_symptoms))

    if not all_new_rows:
        print("\nAll diseases already have enough samples — nothing to add.")
        return

    df_new = pd.DataFrame(all_new_rows)
    for col in df_existing.columns:
        if col not in df_new.columns:
            df_new[col] = 0
    df_new = df_new[df_existing.columns]

    df_merged = pd.concat([df_existing, df_new], ignore_index=True)

    # Verify
    new_counts = df_merged["disease"].value_counts()
    print(f"\nTotal rows: {len(df_existing):,} → {len(df_merged):,} (+{len(all_new_rows):,})")
    print("\nUpdated counts (target diseases):")
    for disease in DISEASE_PROFILES:
        b = existing_counts.get(disease, 0)
        a = new_counts.get(disease, 0)
        print(f"  {disease:<40} {b:>5} → {a:>5}  (+{a-b})")

    df_merged.to_csv(TARGET_CSV, index=False)
    print(f"\nSaved to {TARGET_CSV}")
    print(f"Total: {len(df_merged):,} rows, {df_merged['disease'].nunique()} diseases")
    print("\nNext: python scripts/rebalance_and_retrain.py")


if __name__ == "__main__":
    main()
